org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
android.useAndroidX=true
# Le projet n'utilise aucune dépendance Google Play Services ni AndroidX
# "legacy support" : cette ligne n'est pas nécessaire mais est laissée à false
# explicitement pour rappel.
android.enableJetifier=false
kotlin.code.style=official
